/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./components/profile/AvatarUpload.vue')['default']
    CodeEditor: typeof import('./components/common/CodeEditor.vue')['default']
    CodeViewer: typeof import('./components/common/CodeViewer.vue')['default']
    DatasetInfoCard: typeof import('./components/repo/metadata/DatasetInfoCard.vue')['default']
    DetailedMetadataPanel: typeof import('./components/repo/metadata/DetailedMetadataPanel.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileUploader: typeof import('./components/repo/FileUploader.vue')['default']
    FrameworkCard: typeof import('./components/repo/metadata/FrameworkCard.vue')['default']
    GeneralMetadataAccordion: typeof import('./components/repo/metadata/GeneralMetadataAccordion.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LanguageCard: typeof import('./components/repo/metadata/LanguageCard.vue')['default']
    LicenseCard: typeof import('./components/repo/metadata/LicenseCard.vue')['default']
    MarkdownPage: typeof import('./components/common/MarkdownPage.vue')['default']
    MarkdownViewer: typeof import('./components/common/MarkdownViewer.vue')['default']
    MetadataHeader: typeof import('./components/repo/metadata/MetadataHeader.vue')['default']
    MetricsCard: typeof import('./components/repo/metadata/MetricsCard.vue')['default']
    ReferencedDatasetsCard: typeof import('./components/repo/metadata/ReferencedDatasetsCard.vue')['default']
    RelationshipsCard: typeof import('./components/repo/metadata/RelationshipsCard.vue')['default']
    RepoList: typeof import('./components/repo/RepoList.vue')['default']
    RepoViewer: typeof import('./components/repo/RepoViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarRelationshipsCard: typeof import('./components/repo/metadata/SidebarRelationshipsCard.vue')['default']
    SocialLinks: typeof import('./components/profile/SocialLinks.vue')['default']
    TheFooter: typeof import('./components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
  }
}
