/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/docs/': RouteRecordInfo<'/docs/', '/docs', Record<never, never>, Record<never, never>>,
    '/docs/[slug]': RouteRecordInfo<'/docs/[slug]', '/docs/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/docs/getting-started': RouteRecordInfo<'/docs/getting-started', '/docs/getting-started', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[project]/': RouteRecordInfo<'/projects/[project]/', '/projects/:project', { project: ParamValue<true> }, { project: ParamValue<false> }>,
    '/projects/[project]/[id]': RouteRecordInfo<'/projects/[project]/[id]', '/projects/:project/:id', { project: ParamValue<true>, id: ParamValue<true> }, { project: ParamValue<false>, id: ParamValue<false> }>,
    '/projects/[project]/runs': RouteRecordInfo<'/projects/[project]/runs', '/projects/:project/runs', { project: ParamValue<true> }, { project: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/docs/index.vue': {
      routes: '/docs/'
      views: never
    }
    'src/pages/docs/[slug].vue': {
      routes: '/docs/[slug]'
      views: never
    }
    'src/pages/docs/getting-started.vue': {
      routes: '/docs/getting-started'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/projects/index.vue': {
      routes: '/projects/'
      views: never
    }
    'src/pages/projects/[project]/index.vue': {
      routes: '/projects/[project]/'
      views: never
    }
    'src/pages/projects/[project]/[id].vue': {
      routes: '/projects/[project]/[id]'
      views: never
    }
    'src/pages/projects/[project]/runs.vue': {
      routes: '/projects/[project]/runs'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
