/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/commits': RouteRecordInfo<'/commits', '/commits', Record<never, never>, Record<never, never>>,
    '/DatabaseViewer': RouteRecordInfo<'/DatabaseViewer', '/DatabaseViewer', Record<never, never>, Record<never, never>>,
    '/fallback-sources': RouteRecordInfo<'/fallback-sources', '/fallback-sources', Record<never, never>, Record<never, never>>,
    '/invitations': RouteRecordInfo<'/invitations', '/invitations', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/QuotaOverview': RouteRecordInfo<'/QuotaOverview', '/QuotaOverview', Record<never, never>, Record<never, never>>,
    '/quotas': RouteRecordInfo<'/quotas', '/quotas', Record<never, never>, Record<never, never>>,
    '/repositories': RouteRecordInfo<'/repositories', '/repositories', Record<never, never>, Record<never, never>>,
    '/storage': RouteRecordInfo<'/storage', '/storage', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/commits.vue': {
      routes: '/commits'
      views: never
    }
    'src/pages/DatabaseViewer.vue': {
      routes: '/DatabaseViewer'
      views: never
    }
    'src/pages/fallback-sources.vue': {
      routes: '/fallback-sources'
      views: never
    }
    'src/pages/invitations.vue': {
      routes: '/invitations'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/QuotaOverview.vue': {
      routes: '/QuotaOverview'
      views: never
    }
    'src/pages/quotas.vue': {
      routes: '/quotas'
      views: never
    }
    'src/pages/repositories.vue': {
      routes: '/repositories'
      views: never
    }
    'src/pages/storage.vue': {
      routes: '/storage'
      views: never
    }
    'src/pages/users.vue': {
      routes: '/users'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
